# Generated by Django 5.0.6 on 2024-06-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0006_badge_answer_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], default='Standard', max_length=10),
            preserve_default=False,
        ),
    ]
