# Generated by Django 5.0.6 on 2024-06-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0008_badge_answers_badge_bronze_badges_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='stackbase.tag'),
        ),
    ]
