# Generated by Django 5.0.6 on 2024-06-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0009_tag_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
