# Generated by Django 5.0.6 on 2024-06-15 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0012_remove_badge_answers_question_tags_alter_badge_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='stackbase.question')),
                ('upvotes', models.ManyToManyField(related_name='answer_upvotes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='badge',
            name='type',
            field=models.CharField(choices=[('question', 'Question Badge'), ('answer', 'Answer Badge'), ('participation', 'Participation Badge'), ('tag', 'Tag Badge')], max_length=20),
        ),
        migrations.AddField(
            model_name='badge',
            name='answers',
            field=models.ManyToManyField(related_name='badge_answers', to='stackbase.answer'),
        ),
    ]
